### ISSUE TITLE
Fix quadratic complexity

### ISSUE THREAD

**Issue by Bodigrim** [codedownio/myers-diff#10]
Despite all advances in faster diffing, the algorithm as a whole at the moment is quadratic in time and all thanks to this:
https://github.com/codedownio/myers-diff/blob/600d2c4614266e8412cd3aa64e08f47b7060d4c2/src/Data/Diff/Myers.hs#L56-L58
It's not faster: `VU.fromList (T.unpack left)` is linear, `VU.generate (T.length left) (\i -> T.index left i)` is quadratic.

**Comment by thomasjm** [comment]
Oh whoops, I had it in my head that `T.index` was constant time.

**Comment by thomasjm** [comment]
Thanks for pointing that out!
