### ISSUE TITLE
Clarify comparison to Diff

### ISSUE THREAD

**Issue by Bodigrim** [codedownio/myers-diff#11]
https://github.com/codedownio/myers-diff/blob/600d2c4614266e8412cd3aa64e08f47b7060d4c2/README.md?plain=1#L4
says
> This is a fast Haskell implementation of the Myers text diff algorithm. It is heavily inspired by the Python version in [this post](https://blog.robertelder.org/diff-algorithm/), and should have the same `O(min(len(a), len(b)))` space complexity. (By contrast, the [Diff](https://hackage.haskell.org/package/Diff) package advertises `O(ab)` space complexity.) 

Unfortunately, the documentation of `Diff` has not been updated in line with the updates of the implementation: its space complexity is at most O(max(a, b)), not O(a b). Both packages implement the same Myers' paper, and  - given that we retain O(a + b) bytes of original data anyway - the difference in space complexity between O(max(a, b)) and O(min(a, b)) is not that noticeable. 

It would be great if `README.md` included some benchmarks for both packages.

Cf. https://github.com/seereason/Diff/issues/3

Upd.: Sorry, I realised that my mental model of Myers algorithm may be wrong. The space complexity of `Diff` is definitely not O(a b), but it might be worse than O(max(a, b)), I need to think again.

**Comment by thomasjm** [comment]
Okay, just let me know when you're sure about the `Diff` complexity.

Right, I have this repo all set up to run benchmarks but I haven't gotten around to it yet. Hopefully I'll find time soon.

**Comment by Bodigrim** [comment]
> Okay, just let me know when you're sure about the `Diff` complexity.

As of [`Diff-0.5`](https://hackage.haskell.org/package/Diff-0.5), time complexity is, as usual, $O(N D)$, but space complexity is $O(D^2)$.

**Comment by thomasjm** [comment]
I see. But in the worst case, $D = min(a, b)$, right? So then Diff's space complexity is $O(min(a, b)^2)$ ?

If so, this bound actually sounds worse than the original paper's $O(a + b)$. I guess it can be better in practice when `D` is small though...

Please let me know if I'm off base, it's been a while since I dug into this. If you agree with this basic picture, I'll update the README to explain it.

**Comment by Bodigrim** [comment]
In the worst case $D=max(a,b)$, so yes, worst-case complexity is still quadratic which is fairly bad. It can however be better if $D$ is asymptotically smaller than $min(a,b)$, which is often a case in real world, but far from guaranteed.

I think you can say in README that the worst-case space complexity of `Diff` is quadratic, while `myers-diff` is guaranteed to consume at most linear amount of memory.

(Originally I thought that `Diff` implements the second, divide-and-conquer algorithm from Myers' paper, which would be $max(a,b)$ in memory, but it actually implements the first one which is $D^2$ space. Sorry for confusion)

**Comment by thomasjm** [comment]
Just updated the README. Thanks!

**Comment by thomasjm** [comment]
Hi @Bodigrim,

I've added a first pass at benchmarks now, in case you're interested. Hopefully this can be a jumping-off point to refine the benchmarks or further optimize the implementation. Would love to hear if you have any thoughts.
